version: '3'
services:

  # Artifactory
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 5000:5000
      
  # SSL Proxy
#  proxy:
#    build: proxy
#    image: dockertoolkit/nexus-proxyssl
#    depends_on:
#      - build-ssl-cert
#    ports:
#      - 5002:5002
#    volumes:
#      - ssl-data:/ssl-data
  
  # Key generator
#  build-ssl-cert:
#    build: buildcert
#    image: dockertoolkit/nexus-ssl-cert-gen
#    volumes:
#      - ssl-data:/ssl-data
      
  # Key generator
  config-nexus:
    build: configNexus
    image: dockertoolkit/nexus-config

volumes:
  nexus-data:    { external: { name: nexus-data } }
#  ssl-data:    { external: { name: ssl-data } }